#!/usr/bin/env python3
"""
Regenerate the collective Table of Contents in README.md.

What it does
------------
* Discovers every Markdown note in the repo that is NOT ignored by .gitignore
  (uses `git ls-files`, so the .gitignore rules are honoured automatically),
  excluding README.md itself.
* Groups the notes by the directory they live in ("one heading per directory"),
  ordering both the groups and the notes inside them by *date of creation*
  (first git commit that added the file; falls back to filesystem mtime for
  not-yet-committed files).
* For each note it pulls that note's own "Table of Contents" section and nests
  it underneath the note's entry, rewriting the in-page anchors (`](#foo)`) so
  they point into the file (`](path/to/note.md#foo)`). Notes without a TOC get
  one synthesised from their `##`/`###` headings.
* Writes the result between the AUTO-TOC markers in README.md, leaving anything
  above the markers (the title + intro) untouched.

Run:
    python scripts/generate_readme_toc.py
(from anywhere; paths are resolved relative to the repo root.)
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
README = os.path.join(ROOT, "README.md")

BEGIN = "<!-- BEGIN AUTO-TOC (generated by scripts/generate_readme_toc.py — do not edit by hand) -->"
END = "<!-- END AUTO-TOC -->"

# Friendly labels for directories (fall back to the raw path otherwise).
DIR_LABELS = {
    ".": "Standalone Notes (repository root)",
    "training_llms": "training_llms/ — Training LLMs from Scratch",
}


def sh(args):
    return subprocess.run(args, cwd=ROOT, capture_output=True, text=True).stdout


def list_md_files():
    """All non-ignored .md files (tracked + untracked-but-not-ignored), minus README."""
    tracked = sh(["git", "ls-files", "--cached", "--others", "--exclude-standard", "--", "*.md"])
    files = sorted(set(l.strip() for l in tracked.splitlines() if l.strip()))
    return [f for f in files if os.path.basename(f) != "README.md"]


def creation_ts(relpath):
    """Unix timestamp of the first commit that added the file; mtime if uncommitted."""
    out = sh(["git", "log", "--diff-filter=A", "--follow", "--format=%at", "--", relpath])
    stamps = [int(x) for x in out.split() if x.strip().isdigit()]
    if stamps:
        return stamps[-1]  # oldest (git log is newest-first)
    return int(os.path.getmtime(os.path.join(ROOT, relpath)))


def read_lines(relpath):
    with open(os.path.join(ROOT, relpath), encoding="utf-8") as fh:
        return fh.read().splitlines()


def title_of(lines, relpath):
    for ln in lines:
        m = re.match(r"^#\s+(.*)", ln)
        if m:
            return m.group(1).strip()
    return os.path.basename(relpath)


def slugify(text):
    """Approximate GitHub's heading -> anchor rule."""
    t = text.strip().lower()
    t = re.sub(r"[^\w\s-]", "", t)   # drop punctuation (keeps word chars, spaces, hyphens)
    t = t.replace(" ", "-")
    return t


TOC_LINE = re.compile(r"^\s*([-*]|\d+\.)\s")


def extract_toc(lines):
    """Return the list-item lines of the note's own 'Table of Contents' section, or None."""
    start = None
    for i, ln in enumerate(lines):
        if re.match(r"^#{1,6}\s+.*table of contents", ln, re.IGNORECASE):
            start = i + 1
            break
    if start is None:
        return None
    items = []
    for ln in lines[start:]:
        s = ln.strip()
        if s.startswith("---") or re.match(r"^#{1,6}\s", ln):
            break
        if TOC_LINE.match(ln):
            items.append(ln.rstrip())
        elif s == "":
            continue
        else:
            # any other prose ends the TOC block
            if items:
                break
    return items or None


def synth_toc(lines):
    """Build a TOC from ## / ### headings for notes that lack one."""
    items = []
    for ln in lines:
        m = re.match(r"^(#{2,3})\s+(.*)", ln)
        if not m:
            continue
        text = m.group(2).strip()
        if re.search(r"table of contents", text, re.IGNORECASE):
            continue
        indent = "  " * (len(m.group(1)) - 2)  # ## -> 0, ### -> 2 spaces
        items.append(f"{indent}- [{text}](#{slugify(text)})")
    return items


def reanchor(line, relpath):
    """Rewrite in-page links `](#anchor)` to point into the file, and indent one level."""
    line = re.sub(r"\]\(#", f"]({relpath}#", line)
    return "  " + line  # nest under the file's bullet


def build_block(files):
    # group by directory, remember each group's earliest creation timestamp
    groups = {}
    for relpath in files:
        d = os.path.dirname(relpath) or "."
        groups.setdefault(d, []).append(relpath)

    ordered_dirs = sorted(groups, key=lambda d: min(creation_ts(f) for f in groups[d]))

    out = [BEGIN, ""]
    for d in ordered_dirs:
        label = DIR_LABELS.get(d, f"{d}/")
        out.append(f"### {label}")
        out.append("")
        for relpath in sorted(groups[d], key=lambda f: (creation_ts(f), f)):
            lines = read_lines(relpath)
            title = title_of(lines, relpath)
            out.append(f"- **[{title}]({relpath})**")
            toc = extract_toc(lines)
            if toc is None:
                toc = synth_toc(lines)
            for item in toc:
                out.append(reanchor(item, relpath))
            out.append("")
    out.append(END)
    return "\n".join(out)


def main():
    files = list_md_files()
    block = build_block(files)

    if os.path.exists(README):
        with open(README, encoding="utf-8") as fh:
            existing = fh.read()
    else:
        existing = "# ML Intuitions\n"

    if BEGIN in existing and END in existing:
        head = existing[: existing.index(BEGIN)]
        tail = existing[existing.index(END) + len(END):]
    else:
        # first run: keep whatever is there as the header, then add a Contents heading
        head = existing.rstrip() + "\n\n## Table of Contents\n\n"
        tail = "\n"

    new = head + block + tail
    if not new.endswith("\n"):
        new += "\n"
    with open(README, "w", encoding="utf-8") as fh:
        fh.write(new)

    print(f"Updated {README} — {len(files)} notes across "
          f"{len(set(os.path.dirname(f) or '.' for f in files))} directories.")


if __name__ == "__main__":
    sys.exit(main())
